// <auto-generated />
namespace Movify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoviesDBSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoviesDBSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251032201_MoviesDBSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
